[FIX] 프로필 이미지 수정 시에 기본 이미지가 삭제되는 로직 수정
TeamDon-tBe/SERVER pull request #214
Opened 2024-05-16 16:46 UTC by Hong0329

## 📣 Related Issue

- close #213 

## 📝 Summary

* 원래 이미지가 기본 이미지이고, 그 후에 이미지를 수정할 때 기본 이미지가 삭제되는 로직을 수정했습니다.

## 🙏 Question & PR point

## 📬 Postman

테스트를 해봤는데....스샷을 못찍었네요....믿어주세요....ㅋㅋㅋㅋㅋㅋ

2024-05-17 03:07 UTC, bo-ram-bo-ram approved these changes
믿습니다 아멘

2024-05-18 17:58 UTC, sohyun127 commented
못믿습니다 스샷 올려주세요.

2024-05-18 18:00 UTC, sohyun127 commented
테스트 사진 올려주세요.

2024-05-18 18:00 UTC, sohyun127 requested changes
Request changes

2024-05-18 18:00 UTC, sohyun127 approved these changes

2024-05-19 08:32 UTC, merged